### ISSUE TITLE
Entity export doesn't work anymore

### ISSUE THREAD

**Issue by DavidLeoni** [opendatatrentino/disi-open-data-client#31]
Problem was found in ODR:

```
11:02:2016:19:25:25.043 [Thread-25] ERROR OdrProjOv - Caught exception while exporting to jsonld: 
java.lang.ClassCastException: com.google.gson.JsonArray cannot be cast to com.google.gson.JsonObject
        at eu.trentorise.opendata.disiclient.services.EntityExportService.semantifyJsonObject(EntityExportService.java:101) ~[disi-open-data-client-0.11.1-SNAPSHOT.jar:na]
        at eu.trentorise.opendata.disiclient.services.EntityExportService.convertToJsonLd(EntityExportService.java:84) ~[disi-open-data-client-0.11.1-SNAPSHOT.jar:na]
        at eu.trentorise.opendata.disiclient.services.EntityService.exportToJsonLd(EntityService.java:698) ~[disi-open-data-client-0.11.1-SNAPSHOT.jar:na]
        at eu.trentorise.opendata.opendatarise.ekb.EntityServiceController.exportToJsonLd(EntityServiceController.java:48) ~[classes/:na]
        at eu.trentorise.opendata.opendatarise.model.CommitProcess.run(CommitProcess.java:125) ~[classes/:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
11:02:2016:19:25:25.043 [Thread-25] INFO  OdrProjOv - 


```

**Comment by DavidLeoni** [comment]
closed in branch-0.11
