### ISSUE TITLE
TransactionSystemException: Oops! Something went wrong

### ISSUE THREAD

**Issue by DavidLeoni** [opendatatrentino/disi-open-data-client#32]
Most probably it's just a server issue, putting it here for reference. This seems to happen when the server is clogged:

```
12:02:2016:12:25:42.856 [qtp13995775-58] WARN  command - Exception caught
org.springframework.transaction.TransactionSystemException: Oops! Something went wrong, please contact the developer.
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_80]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_80]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_80]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_80]
        at it.unitn.disi.sweb.webapi.client.HttpErrorHandler.handleError(HttpErrorHandler.java:69) ~[sweb-webapi-commons-client-3.0.1-RELEASE.jar:na]
        at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:556) ~[spring-web-3.2.8.RELEASE.jar:3.2.8.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:514) ~[spring-web-3.2.8.RELEASE.jar:3.2.8.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:485) ~[spring-web-3.2.8.RELEASE.jar:3.2.8.RELEASE]
        at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:251) ~[spring-web-3.2.8.RELEASE.jar:3.2.8.RELEASE]
        at it.unitn.disi.sweb.webapi.client.HttpClient.performGet(HttpClient.java:120) ~[sweb-webapi-commons-client-3.0.1-RELEASE.jar:na]
        at it.unitn.disi.sweb.webapi.client.AbstractApiClient.readList(AbstractApiClient.java:122) ~[sweb-webapi-commons-client-3.0.1-RELEASE.jar:na]
        at it.unitn.disi.sweb.webapi.client.AbstractApiClient.readList(AbstractApiClient.java:105) ~[sweb-webapi-commons-client-3.0.1-RELEASE.jar:na]
        at it.unitn.disi.sweb.webapi.client.kb.ConceptClient.readConcepts(ConceptClient.java:84) ~[sweb-webapi-kb-client-3.0.1-RELEASE.jar:na]


```

**Comment by DavidLeoni** [comment]
Corrections: it happens when debugger stops program execution and connection is lost !
