### ISSUE TITLE
sweb.webapi.model.eb.Entity cannot be cast to Structure

### ISSUE THREAD

**Issue by DavidLeoni** [opendatatrentino/disi-open-data-client#35]
Bad cast found in ODR, remember sweb `Entity` is _NOT_ a descendant of `Structure`

```
java.lang.ClassCastException: it.unitn.disi.sweb.webapi.model.eb.Entity cannot be cast to it.unitn.disi.sweb.webapi.model.eb.Structure
        at eu.trentorise.opendata.disiclient.services.EntityService.readStructure(EntityService.java:298) ~[disi-open-data-client-0.11.1-20160307.154158-84.jar:na]
        at eu.trentorise.opendata.disiclient.model.entity.EntityODR.<init>(EntityODR.java:186) ~[disi-open-data-client-0.11.1-20160307.154158-84.jar:na]
        at eu.trentorise.opendata.disiclient.model.entity.EntityODR.<init>(EntityODR.java:193) ~[disi-open-data-client-0.11.1-20160307.154158-84.jar:na]
        at eu.trentorise.opendata.disiclient.services.EntityService.readEntities(EntityService.java:234) ~[disi-open-data-client-0.11.1-20160307.154158-84.jar:na]
        at eu.trentorise.opendata.opendatarise.ekb.EntityServiceController.readEntities(EntityServiceController.java:174) ~[classes/:na]
        at eu.trentorise.opendata.opendatarise.commands.ReadEntitiesCommand.doGet(ReadEntitiesCommand.java:46) ~[classes/:na]
        at com.google.refine.RefineServlet.service(RefineServlet.java:533) [main-0.3.6-SNAPSHOT.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [jetty-runner.jar:9.2.10.v20150310]
```

**Comment by DavidLeoni** [comment]
Fixed in branch-0.11
